---
title: "Plotting differences of rasters"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting differences of rasters}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::clean_cache(clean = TRUE)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.dim = c(8, 6)
)

```

```{r setup}
library(magrittr)
library(mhwci)
library(ggplot2)

```

```{r create_rasters_from_db, echo=TRUE}

# read from the environment
db_file <- mhwci::get_dbfile()
print(db_file)
try(dbDisconnect(db))
db<- mhwci::mhw_connect(db_file)

# this may take signifigant memory
arise10_raster_list <- durations_by_decade_raster(db, mhw_table = "arise10_decade_metrics")
arise15_raster_list <- durations_by_decade_raster(db, mhw_table = "arise15_decade_metrics")
ssp245_raster_list <- durations_by_decade_raster(db, mhw_table = "ssp245_decade_metrics")

ssp245_raster_list
```


```{r, diffplot, fig.alt = "difference in mean duration SSP2 4.5 minus ARISE1.5", echo=TRUE}
arise_diff <- ssp245_raster_list - arise15_raster_list 
plot_rasters_squish_outliers(arise_diff, 
                             title = "SSP2 4.5 minus ARISE1.5", 
                             subtitle = "",
                             scale_label = "", 
                             palette="water",
                             max_threshold_value = 500,
                             break_width = 50
                             )

```


There is not a red-white-blue color scheme, this is using the 'water' palette.  You could also try the 'blues' palette. 


### Difference Density plots

This is not the best way to do this.   The density plot requires the database to be in 'long form' or 
```
value decade
 3     2040
 2     2040
 ...
 3.1   2050
 etc
 ```
 
This does not remove outliers so it's hard to visualize 

Note it requires the 'reshape' package, which you may have to install

```{r}
library(reshape)
```


```{r, densityplot,fig.alt = "density plot diff in mean duration SSP2 4.5 and ARISE 1.5" , echo=TRUE}

diff_values<- data.frame(lapply(arise_diff, terra::values))
names(diff_values)<- decades  
diff_values_long_form <- na.omit(reshape::melt(diff_values))

#plot full range of difference, which includes a huge range

g<- ggplot(diff_values_long_form , aes(x=value, fill=variable)) + geom_density(na.rm = TRUE, alpha = 0.25)
print(g)

# this just strips out the outliers, which removes data, but it looks nicer
g+ xlim(-100, 500)


```
```{r, database-cleanup}
# database cleanup
rm(arise10_raster_list, arise15_raster_list,ssp245_raster_list, arise_diff)
rm(diff_values, diff_values_long_form)
try(dbDisconnect(db), silent= TRUE)

```
